"""Implement CLI: materialize concrete artifacts from generated IR."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List

from .materialize.materializer import materialize_execution_plans


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="spec-to-ir-implement",
        description="Materialize concrete Broadway/Python/Java implementations from generated IR",
    )
    p.add_argument("--in-ir", required=True, help="Input IR JSON path generated by spec-to-ir")
    p.add_argument("--out-dir", required=True, help="Output directory for materialized artifacts")
    p.add_argument("--canonical-ddl", required=False, help="Canonical DDL path for K2 table generation")
    p.add_argument("--runtime", action="append", default=[], help="Runtime to materialize (repeatable)")
    return p


def main(argv: List[str] | None = None) -> None:
    args = build_arg_parser().parse_args(argv)
    in_ir = Path(args.in_ir).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve()
    canonical_ddl = Path(args.canonical_ddl).expanduser().resolve() if args.canonical_ddl else None
    out_dir.mkdir(parents=True, exist_ok=True)

    result = materialize_execution_plans(
        in_ir,
        out_dir,
        runtimes=args.runtime or None,
        canonical_ddl_path=canonical_ddl,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
